

Use reviewsDatabase;

CREATE TABLE Uni(
   id INT NOT NULL AUTO_INCREMENT,
   PRIMARY KEY (id),
   Ranks                       INTEGER  NOT NULL  
  ,Institution                 VARCHAR(70) NOT NULL
  ,Entry_Standards             INTEGER  NOT NULL
  ,Student_Satisfaction        NUMERIC(4,2)
  ,Research_Quality            NUMERIC(4,2)
  ,Research_Intensity          NUMERIC(4,2)
  ,Graduate_prospects_outcomes NUMERIC(4,1) NOT NULL
  ,Graduate_prospects_on_track NUMERIC(4,1) NOT NULL
  ,StudentStaff_Ratio          NUMERIC(4,1) NOT NULL
  ,Academic_Services_Spend     INTEGER  NOT NULL
  ,Facilities_Spend            INTEGER  NOT NULL
  ,Degree_Completion           NUMERIC(4,1) NOT NULL
  ,Overall_Score               INTEGER  NOT NULL
);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (1,'University of Oxford',201,NULL,3.49,0.95,88.3,81.4,10.5,2748,546,98.8,1000);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (2,'University of Cambridge',207,NULL,3.53,1,87.5,81.2,11.6,2705,1067,98.9,995);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (3,'London School of Economics and Political Science, University of London',193,3.87,3.53,0.65,90.2,78.9,13.4,1822,805,97.2,960);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (4,'University of St Andrews',209,4.26,3.31,0.71,78.6,80.1,11.8,2803,705,96.3,927);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (5,'Imperial College London',198,4.05,3.63,0.8,92.4,84.6,11.7,2855,618,98.8,913);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (6,'Durham University',187,3.9,3.34,0.7,82.5,79.8,13.7,2278,989,97.9,902);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (7,'Loughborough University',155,4.06,3.3,0.71,79.2,77.8,13.8,1981,1395,93.4,876);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (8,'University of Bath',177,3.99,3.31,0.73,85.8,81.6,15.4,1930,790,96.5,867);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (9,'UCL (University College London)',189,3.85,3.5,0.72,85.3,80.1,11.1,2175,322,95.8,860);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (10,'University of Warwick',167,4,3.42,0.59,83.4,81.1,14.2,1577,820,96.7,842);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (11,'Lancaster University',150,3.96,3.37,0.8,75.8,76.2,14.1,2158,952,95.8,836);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (12,'The University of Edinburgh',190,3.7,3.42,0.76,76.8,77.7,11.5,1426,789,96.4,809);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (13,'University of Southampton',155,3.89,3.41,0.71,75.4,73.8,12.6,2142,823,93.6,793);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (14,'University of Birmingham',158,3.67,3.43,0.63,76.5,78.3,14.9,2385,1090,96.9,772);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (15,'University of Bristol',167,3.78,3.51,0.67,79,77.9,14.1,1582,716,97.1,771);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (16,'University of Leeds',159,3.81,3.35,0.65,78.2,75.8,13.8,2684,433,95.2,768);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (17,'University of Manchester',165,3.71,3.47,0.66,78.4,76.2,14.3,2371,621,95.6,763);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (18,'University of Surrey',143,3.98,3.29,0.62,80.2,79.6,16,2052,718,92.7,759);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (19,'University of Exeter',162,3.81,3.35,0.69,74.6,74.4,15.8,1282,1052,95.7,754);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (20,'University of York',149,3.92,3.45,0.65,76.2,76.3,15.1,1168,679,95.2,752);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (21,'University of Liverpool',144,3.89,3.34,0.61,73.3,76.2,13.8,2370,714,94.9,741);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (22,'King''s College London, University of London',165,3.75,3.46,0.69,82.4,79.9,13.9,1908,705,95,739);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (23,'University of Glasgow',204,3.93,3.43,0.57,72.2,74.5,13.7,1758,592,93.5,726);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (24,'Queen''s University Belfast',148,3.87,3.27,0.7,81.2,80.1,15.9,1417,740,95,724);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (25,'University of Nottingham',152,3.8,3.34,0.68,79.3,76.8,15.8,1845,868,95.7,722);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (26,'Cardiff University',148,3.73,3.36,0.59,79.5,78.8,14.5,1711,704,94.8,719);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (27,'University of East Anglia UEA',134,3.86,3.38,0.56,73,73.2,14.2,1823,1070,91.9,715);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (28,'University of Sheffield',149,3.91,3.4,0.66,74.4,75.3,14.9,1823,529,93.7,712);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (29,'University of Leicester',129,3.9,3.3,0.63,71.2,74.4,13.7,2356,716,93.1,711);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (29,'Harper Adams University',128,3.94,2.61,0.25,74.3,83.8,13.8,2004,2083,92.9,711);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (31,'University of Reading',129,3.76,3.24,0.63,74.6,76,16.6,1911,855,94,704);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (32,'University of Strathclyde',207,3.97,3.29,0.65,76.7,75.2,19.1,1541,498,94.2,698);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (33,'Royal Holloway, University of London',128,3.86,3.3,0.7,68,71.3,16.2,1810,765,95.6,694);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (34,'Heriot-Watt University',176,3.86,3.22,0.67,72.1,75,18,2032,1380,89,686);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (35,'Queen Mary University of London',145,3.8,3.39,0.61,73.4,74.4,14.6,2101,662,95.8,683);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (36,'Newcastle University',148,3.67,3.29,0.7,73.8,74.5,14.7,1932,567,95.4,682);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (37,'University of Aberdeen',185,3.98,3.03,0.73,71.6,72.4,15,1860,730,92.7,680);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (38,'University of the Arts London',135,3.66,3.18,0.14,58.2,67.4,11.9,2933,281,88.2,679);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (39,'University of Essex',112,3.76,3.23,0.65,65.3,71.3,16,2044,1350,89.3,674);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (40,'City, University of London',133,3.73,3.25,0.56,77.7,79.6,19.4,1882,612,94.3,667);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (41,'University of Sussex',135,3.78,3.29,0.69,66.8,66.4,17.3,1544,873,92.4,665);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (42,'Swansea University',131,3.95,3.2,0.47,71.5,73.3,16.2,1485,609,91,651);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (43,'Northumbria University, Newcastle',133,3.73,3.06,0.68,71.4,76.1,15.7,1575,621,85.3,649);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (44,'Ulster University',131,3.98,3.2,0.55,70.3,74.8,20.3,1665,661,90.5,642);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (45,'Oxford Brookes University',122,3.74,2.87,0.39,73.7,77.8,14,1415,789,91,640);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (46,'SOAS University of London',140,3.83,3.24,0.57,68,70.5,14.6,2601,457,87.6,637);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (47,'University of Kent',123,3.89,3.26,0.67,65.1,69.5,17.7,1294,759,92.7,636);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (48,'Aston University, Birmingham',133,3.82,3.06,0.52,75.5,77.9,17,1452,547,93.1,633);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (49,'University of Dundee',180,3.87,3.23,0.41,73.8,76.1,14.9,1850,638,90.2,632);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (50,'University of Stirling',169,3.93,3.11,0.67,66.4,73.9,18.6,1030,842,89.9,631);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (51,'University of Lincoln',125,3.91,2.98,0.39,65.2,71.7,16.1,1316,816,90.4,630);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (52,'Keele University',127,3.91,3.07,0.52,74.4,77.9,15.3,1494,619,91.7,621);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (53,'Aberystwyth University',125,4.09,3,0.69,61.2,67.2,15.6,2367,473,85.6,615);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (54,'Norwich University of the Arts',131,3.94,2.96,0.13,56.9,65.7,15.5,1963,700,86.1,611);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (55,'St George''s, University of London',145,3.53,3.23,0.38,94.6,93.2,13.1,2088,335,95.2,607);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (56,'Nottingham Trent University',123,3.8,3.1,0.2,62.5,69.7,15.3,1287,782,89.8,606);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (57,'Coventry University',121,3.93,2.9,0.23,68.4,73,13.8,1958,611,80.2,605);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (58,'University of Hull',125,3.92,3.1,0.37,70.3,74.3,16.2,1925,858,82.7,598);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (59,'University of Huddersfield',126,3.76,2.8,0.47,62.8,71.8,14.7,1828,716,86.6,595);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (60,'University of Chester',123,3.84,2.5,0.48,66.3,72.6,15.1,2000,869,87.3,594);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (61,'Bristol, University of the West of England',123,3.9,2.96,0.25,72.8,74.5,15.7,1085,557,86.2,586);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (62,'Goldsmiths, University of London',124,3.6,3.11,0.64,57.6,66,13.9,2389,859,77.6,585);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (63,'Bangor University',122,3.87,3.23,0.46,61.8,67.1,15.1,1376,849,84.2,584);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (64,'University of Plymouth',132,3.89,3.01,0.45,70.9,76.1,17.3,1900,542,87.9,581);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (64,'Edge Hill University',128,3.87,2.67,0.32,63.4,71.2,15.5,1584,890,87.7,581);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (66,'Sheffield Hallam University',118,3.77,2.93,0.28,72.1,74.8,17.7,2214,439,88,577);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (67,'Manchester Metropolitan University',123,3.74,3.11,0.36,61.5,67.5,17.5,2057,731,87.3,574);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (68,'University of Hertfordshire',113,3.89,3.02,0.32,67.9,73.5,16.5,1519,967,86.3,571);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (69,'University of Portsmouth',119,3.79,3,0.41,65.4,70.4,16.8,1528,638,87.8,567);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (70,'Falmouth University',127,3.88,3.17,0.2,52.7,63.1,14.8,1528,511,84.7,565);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (71,'Arts University Bournemouth',148,3.84,2.63,0.2,52.9,61.1,14.5,1409,324,88.7,563);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (72,'Bournemouth University',116,3.6,2.77,0.66,71.2,72.4,19.2,1672,718,87,562);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (72,'Cardiff Metropolitan University',124,3.86,2.83,0.28,64.4,72,18.1,1685,750,82.1,562);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (74,'University of Bradford',129,3.87,2.85,0.53,69.1,76.5,19.1,1274,662,91,549);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (74,'University for the Creative Arts',129,3.86,3.06,0.11,49.9,57.5,13.8,2291,204,85.1,549);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (76,'University of Chichester',129,4.03,2.41,0.36,59.3,68.9,15.2,1042,739,86.2,546);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (77,'University of West London',117,4.04,2.67,0.13,60.6,68.6,12.9,1530,734,76.5,545);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (78,'University of Roehampton',105,3.84,3.11,0.44,57.1,66.6,18.3,2302,863,80.8,539);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (78,'Kingston University',120,3.87,2.89,0.39,65.8,69.6,17,1936,683,82.9,539);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (80,'Liverpool John Moores University',132,3.78,2.82,0.45,63.4,69.5,18,1226,405,85.9,538);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (81,'Brunel University London',123,3.55,2.88,0.75,65.1,72.9,17.9,1118,495,89.4,535);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (81,'University of Brighton',117,3.62,3.05,0.4,70.8,72.1,18.1,1801,579,86,535);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (83,'University of Greenwich',121,3.87,2.86,0.51,68.4,72.8,19.5,1229,628,86.8,534);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (83,'University of Sunderland',122,4,2.75,0.13,56.2,70,15.9,1911,553,80.1,534);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (85,'University of Worcester',123,3.96,2.32,0.34,70.9,76.8,17.5,1217,607,84.9,533);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (85,'University of Salford',124,3.77,3,0.27,68,73,17.9,1263,701,83.9,533);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (87,'St Mary''s University, Twickenham',112,4.07,2.72,0.47,65.6,72.4,16,1164,776,74.2,531);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (88,'Glasgow Caledonian University',170,3.89,2.95,0.31,73.6,77.2,22.9,1465,273,88.9,529);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (89,'Liverpool Hope University',117,3.82,2.52,0.62,56.7,73.9,16.3,811,1182,83.5,525);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (89,'Birmingham City University',122,3.88,2.7,0.19,67.7,72.5,17.2,1293,530,86.6,525);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (91,'University of Derby',123,3.95,2.52,0.25,62.8,71.4,15.8,1362,394,83.2,523);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (91,'University of South Wales',127,3.86,2.66,0.21,61.9,70.9,16.1,1710,282,81.6,523);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (93,'Queen Margaret University, Edinburgh',161,3.97,2.59,0.37,64.5,74.1,21.9,1040,397,88.1,519);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (94,'Teesside University, Middlesbrough',119,3.74,2.76,0.32,70,76.8,17.1,1956,479,80.2,517);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (95,'Royal Agricultural University',117,3.76,2.33,0.53,61.6,80.8,21.5,2292,963,92.3,515);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (95,'Bath Spa University',124,3.81,2.71,0.46,52.4,65.3,16.6,1674,547,82.1,515);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (97,'Edinburgh Napier University',148,3.99,2.86,0.45,69,70.3,22.1,1898,309,87.5,504);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (98,'University of Northampton',112,3.77,2.22,0.24,67.4,76.9,17.7,1907,698,86.2,501);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (99,'University of Central Lancashire',125,3.8,2.81,0.3,63.2,69.9,16.2,1679,423,79.7,498);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (100,'University of Suffolk',110,3.85,2.69,0.12,73.4,77.3,15,2165,531,66.7,495);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (101,'University of Gloucestershire',118,3.88,2.43,0.31,60.8,68.6,17.2,1529,439,81.8,493);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (102,'Staffordshire University',116,3.95,2.78,0.17,63.5,68.5,17.7,1360,474,79,489);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (103,'Robert Gordon University',153,4.02,2.54,0.17,69.9,76.1,20.8,1170,481,86.8,488);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (103,'York St John University',112,3.94,2.43,0.47,61.3,69.1,18,1467,568,86.4,488);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (105,'Canterbury Christ Church University',108,3.76,2.72,0.32,67,75.3,18.2,1462,550,83.8,486);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (106,'Leeds Beckett University',113,3.85,2.68,0.36,64.4,68.7,21.7,1470,684,84.4,485);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (107,'Buckinghamshire New University',112,3.92,2.25,0.13,63.3,72,15.4,2591,581,70.6,479);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (108,'Abertay University',150,3.95,2.66,0.64,64.3,70.1,24.2,1023,645,81.8,477);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (109,'University of Winchester',115,3.74,2.53,0.38,61.3,68.5,18.1,1194,452,87.4,474);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (110,'De Montfort University',108,3.64,2.69,0.39,62.2,67.9,18.5,1350,919,84.5,471);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (111,'University of Westminster, London',116,3.76,3,0.47,54.3,64.1,19.9,1261,543,85,465);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (112,'Middlesex University',109,3.79,2.78,0.45,55.7,67.3,17.1,2384,345,75.6,463);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (113,'Plymouth Marjon University',118,4.08,2.49,0.29,58.7,72.4,19.2,618,350,83.3,457);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (114,'Anglia Ruskin University',109,3.92,2.81,0.24,68.9,76.2,19.4,1267,480,78.2,454);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (115,'University of Buckingham',111,4.03,NULL,NULL,83.2,88.5,18.5,841,466,87.1,448);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (116,'London South Bank University',107,3.74,2.78,0.23,64.8,71.8,17.5,1696,282,85.1,443);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (117,'Solent University (Southampton)',116,3.87,2.16,0.25,56.5,62.9,17.5,1408,727,80.8,442);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (118,'Bishop Grosseteste University',102,3.84,1.92,0.39,67.2,77.2,19.8,1276,855,89.4,421);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (118,'University of Cumbria',120,3.81,2.3,0.25,66.3,75.3,18.7,1227,319,85,421);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (120,'University of Wales Trinity Saint David',139,3.97,2.5,0.1,55.2,69.1,21.1,1096,401,75.7,419);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (121,'University of Wolverhampton',112,3.83,2.56,0.35,61.7,68.4,16.5,1748,318,72.7,414);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (122,'Newman University, Birmingham',109,3.97,2.03,0.43,59.6,72.8,18,1486,341,79.7,402);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (123,'London Metropolitan University',96,4.07,2.63,0.2,52.9,67.1,21.4,2314,954,70.2,388);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (124,'University of Bolton',114,4.03,1.89,0.2,55.8,66.4,16.4,1381,478,77.3,370);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (125,'University of the West of Scotland',140,3.75,2.48,0.45,65.5,72.3,23.5,1703,460,78.7,369);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (126,'University of East London',107,3.86,2.58,0.35,55.1,67.4,26.2,988,572,78.8,332);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (127,'Glyndwr University, Wrexham',107,4.1,2.19,0.32,59.1,70.3,24.9,972,398,75.6,320);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (128,'University of Bedfordshire',108,3.83,2.71,0.23,64.4,72.4,24.3,1197,480,62.6,310);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (128,'Leeds Trinity University',111,3.74,2.11,0.37,56.2,66.8,21.5,1256,386,72.2,310);
INSERT INTO Uni(Ranks,Institution,Entry_Standards,Student_Satisfaction,Research_Quality,Research_Intensity,Graduate_prospects_outcomes,Graduate_prospects_on_track,StudentStaff_Ratio,Academic_Services_Spend,Facilities_Spend,Degree_Completion,Overall_Score) VALUES (130,'Ravensbourne University London',111,3.54,2.2,0.17,59.6,71.8,24.6,1150,309,79,300);

INSERT INTO forum (firstname, surname, username,topic_title,post_date,post_content)
VALUES  ('Shad','Travis','shaddy','Campus Accessibility', '2021-11-01 12:53', 'THIS IS NOT ACCESSIBLE FOR DISABLE PEOPLE AT ALL!!!'),
		('Bernadette','Bagley','baggy','Facilities','2021-11-07 16:26', 'They have really intriguing buildings..'),
		('Rolo','Vicario','roly','Faculty','2021-11-13 17:01', 'The professor teaching software project is awesome!'),
		('Sophie','Panza','panny','Graduate prospects', '2021-11-03 10:34', 'I did not get a job after university…'),
		('Miriana','Vitali','vit','Student satisfaction','2021-11-13 19:45', 'I really recommend people to study here! Good vibe and I love the campus');
